default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/hashable_development

test:
  <<: *default
  database: db/hashable_test

production:
  <<: *default
  database: db/hashable_production %>
