default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/twitter_copycat_development

test:
  <<: *default
  database: db/twitter_copycat_test

production:
  <<: *default
  database: db/twitter_copycat_production %>
